server:
  port: 8761



eureka:
  instance:
    hostname: Cloud01-Eureka-Server #实例的主机名
  client:
    register-with-eureka: false   #是否将自己注册到eureka服务器上
    fetch-registry: false         #指示该客户端是否应从eureka服务器获取eureka注册表信息
    service-url:
      defaultZone: http://localhost:8761/eureka/   #这就是默认的注册中心地址


spring:
  application:
    name: eureka-server


